server:
  port: 9090

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: student-service
          uri: 'http://localhost:8081'
          predicates:
            - Path=/student/**
#            - Query=src,mobile
#            - Query=version,2
        - id: department-service
          uri: 'http://localhost:8082'
          predicates:
            - Path=/department/**
  config:
    import:
      "optional:configserver:http://localhost:8888"


management:
  endpoints:
    web:
      exposure:
        include: '*'
